### ISSUE TITLE
Nonexistant function 'finalize' in SignalCollector when debugging test function

### ISSUE THREAD

**Issue by jmb462** [AdrienQuillet/godot-simple-test-harness#15]
`assert_that_signal(node.signal).has_been_emitted_only_once()` raise an error when debugging but not when launching the test whithout debug.

`Invalid call. Nonexistant function 'finalize' in base 'RefCounted (SignalCollector)'.`
(test_case.gd line 105)

In the following video, first launch succeeds without debug and second launch failed with debug (OBS didn't capture the context menu)
https://user-images.githubusercontent.com/3649998/219974929-f644105c-ab81-45df-abcd-a3276cf07ce3.mp4

How to reproduce : 

Test :
 ```swift
func test_extrude_changed_emit_extrude_changed_signal() -> void:
	collect_signals_of(buffer)
	buffer.spawn_extruded_blocks()
	assert_that_signal(buffer.extrude_changed).has_been_emitted_only_once()
```

Called function just emitting the extrude_changed signal.

**Comment by Earewien** [comment]
There was a typo in `SignalCollector` `finalize` function, causing this issue.
Reproduce in a unit test, and fixed

My bad 😥
